version: '3.8'

services:
  flask:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000" # Map Flask app to localhost:5000
    depends_on:
      - redis
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app # Mount local directory for development (optional)

  celery:
    build: .
    container_name: celery_worker
    command: celery -A celery_worker.celery worker --loglevel=info
    depends_on:
      - flask
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Map Redis default port
    volumes:
      - redis_data:/data # Persist Redis data (optional)

volumes:
  redis_data:
